from schemas.booking_schema import PlainBookingSchema
from schemas.customer_schema import PlainCustomerSchema
from schemas.employee_schema import PlainEmployeeSchema
from schemas.invoice_schema import PlainInvoiceSchema
from schemas.tasks_schema import PlainTaskDoneSchema,PlainNewTaskSchema
from schemas.cashier_schema import PlainCashierSchema